name: Build Net8 Variants

on:
  workflow_dispatch:

jobs:
  selfcontained:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: '8.0.x'

    - name: Publish self-contained exe
      run: dotnet publish ./src/PruebaNet8.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Upload artifact (self-contained)
      uses: actions/upload-artifact@v4.3.1
      with:
        name: PruebaNet8-selfcontained
        path: src/bin/Release/net8.0/win-x64/publish/


  frameworkdependent:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: '8.0.x'

    - name: Publish framework-dependent exe
      run: dotnet publish ./src/PruebaNet8.csproj -c Release

    - name: Upload artifact (framework-dependent)
      uses: actions/upload-artifact@v4.3.1
      with:
        name: PruebaNet8-frameworkdependent
        path: src/bin/Release/net8.0/publish/
